Ajustes de tratamentos de erros e parse de vars double
kauereblin/SuperCompilador pull request #1
Opened 2022-12-08 03:26 UTC by luizklitzke1

- Ajustados tratamentos de erro para tipos em operações.
- Adicionado catch dummy para ignorar erro ao compilar sem ter salvo arquivo
- Criada formatação para garantir formato do parse de double independentemente do sistema operacional.

2022-12-08 11:25 UTC, kauereblin requested changes

2022-12-08 11:25 UTC, kauereblin commented on Semantico.cs
> +                        string lexema = token.getLexeme();
única coisa válida

2022-12-08 17:00 UTC, luizklitzke1 commented on Semantico.cs
> +                        string lexema = token.getLexeme();
![image](https://user-images.githubusercontent.com/49824305/206516010-f494f6a5-a736-4ce4-9897-7f73f7457485.png)

2022-12-09 02:24 UTC, kauereblin approved these changes

2022-12-09 02:25 UTC, merged